project:
  type: website
  output-dir: docs

website:
  title: "Shimeng Huang"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - software.qmd
      - biography.qmd
  search: 
    location: navbar
    type: overlay
  repo-url: https://github.com/shimenghuang/shimenghuang.github.io
  repo-actions: [edit, issue]

format:
  html:
    theme: journal
    css: styles.css
    toc: true



